### ISSUE TITLE
Error on setting quota

### ISSUE THREAD

**Issue by j0hannes** [ekenberg/quotatool#15]
When called like this

> quotatool -u username -b -q 10G -l 11G /some/partition

quotatool (version 1.4.12) fails for some users with the error message

> quotatool: Failed setting quota (generic): No such process

and exit code 3.

**Comment by jasontibbitts** [comment]
I'm getting something similar:

```
> sudo quotatool -u josic -b -q 1k -l 1k /export/h-tibbs
quotatool: Error while detecting kernel quota version: No such process
```

This is on Fedora 24, an ext4 filesystem which is of course quota-enabled:

```
/dev/sdd1 /export/h-tibbs ext4 rw,seclabel,noatime,discard,data=ordered,jqfmt=vfsv1,usrjquota=aquota.user 0 0
```

It worked in Fedora 23 (on the same machine and filesystem) running kernel 4.6.5, but not in Fedora 24 running kernel 4.6.6.  The version of quotatool is 1.6.2; the package was rebuilt for F24 but there were otherwise no changes to the packaging.  That does mean that the F24 version was built with gcc 6.1, which could be a potential issue.  I'll try just pulling the F23 package and see if it makes any difference, just to rule that out.

**Comment by ekenberg** [comment]
@j0hannes: Did you ever try this with the latest version? 1.4.12 is rather old. If error persists with the latest code, please supply instructions for recreating the problem so I can test it?

**Comment by ekenberg** [comment]
@jasontibbitts: not sure how to replicate that error - `ESRCH (No such process)` returned from a *kernel syscall* so it's not quotatool, and ESRCH almost always means there is something wrong with the kernel (no quota support) or the filesystem (quota not enabled or not correctly setup in some other way). If I can somehow recreate the error myself I might be able to debug it.

**Comment by ekenberg** [comment]
@j0hannes @jasontibbitts : to both of you, sorry for getting back years after you posted - I had some severe health issues and had to cut back on activities.

**Comment by j0hannes** [comment]
@ekenberg we use the version provided by Debian 8; Debian 9 will most likely ship with a more recent version. Nonetheless I can't reproduce the error anymore. I wish you all the best!
