### ISSUE TITLE
quotatool: Failed Fetching quotas: No such file or Directory. 

### ISSUE THREAD

**Issue by amrik06** [ekenberg/quotatool#22]
quotatool not working for AIX.
AIX Version:- 7200-04-01-1939  ( IBM Power PC )

quotatool Version - 1.6.2

Whenver i follow all the syntax and argument, quotatool reports following error all the time
<img width="504" alt="quotatool-AIX" src="https://user-images.githubusercontent.com/92379829/169778755-58887599-da76-4dfb-8651-7792fb354259.PNG">

quotatool: Failed Fetching quotas: No such file or Directory.

I trying using different arguments as per quotatool Help, but all command output reports same thing:
quotatool: Failed Fetching quotas: No such file or Directory.

**Comment by ekenberg** [comment]
Could you please retry with debug output, add `-v -v` to command line options

**Comment by amrik06** [comment]
<img width="471" alt="quotatool-AIX-vvv" src="https://user-images.githubusercontent.com/92379829/169995769-5fda6481-c543-4f18-822b-5cdab17914de.PNG">

Attaching quotatool output with -vvv option.

JFYI,
We are using JFS2 filesystem of AIX.

Please share your views on priority.

**Comment by ekenberg** [comment]
This is another command though, the first one on /data resulted in "no such file or directory", this one is on /home and gives a different error. Would you please re-run the first command with debugging, just to see more details. Does /data/quota.user even exist?

I'm not at all sure I can fix this since I do not have access to AIX. The most common issue historically is that users have not implemented quotas correctly or at all. The second most common is changed system API because of kernel changes.

**Comment by ekenberg** [comment]
Thank you. Looking at the source code for quotatool, there is currently no support for JFS2. I would love to implement it, but I do not have access to any AIX system for development and testing. The AIX part of quotatool was written before I took over as maintainer. AFAIK there is no way I can download an AIX-image and boot it in Virtualbox on my laptop (?). Would love to fix it but not sure how to go about it.

Note to self: https://www.ibm.com/docs/en/aix/7.2?topic=q-quotactl-subroutine
